#! /usr/bin/python

# Script to drop a given MySql database and user. See README.md
# for more details.
#
# Author: Mark Phillips <mphillip@unca.edu>

import sys, re, os
sys.path.append(".") # this line gets replaced by `make install`
import drutils

def usage():
    print "usage: dbdrop [--dbsu=USER:PASSWORD] NAME"
    drutils.common_usage();
    sys.exit(-1)

if __name__ == "__main__":
    #
    # Process the arguments
    #
    DB_SU    = None
    DB_SU_PW = None
    NAME     = None
    sys.argv.pop(0)
    while True:
        if len(sys.argv)==0:
            break
        arg = sys.argv.pop(0)
        if arg.startswith("--dbsu"):
            match = re.match(r'^--dbsu=([^:]+):(.*)$', arg)
            if match:
                DB_SU    = match.group(1)
                DB_SU_PW = match.group(2)
            else:
                usage()
        else:
            if NAME==None:
                NAME = arg
            else:
                usage()
    #
    # If we didn't get DB_SU info from the args, check for it in environment vars:
    # 
    if DB_SU==None:
        try:
            DB_SU    = os.environ['DRUTILS_DB_SU']
            DB_SU_PW = os.environ['DRUTILS_DB_SU_PW']
        except:
            pass

    user_exists = drutils.database_user_exists(NAME, DB_SU, DB_SU_PW)
    database_exists = drutils.database_exists(NAME, DB_SU, DB_SU_PW)

    if user_exists and database_exists:
        if drutils.confirm_with_yes("really drop database and user '%s'? [NO|yes] " % NAME):
            drutils.drop_database(NAME, DB_SU, DB_SU_PW)
            print "dropped database '%s'" % NAME;
            drutils.drop_user(NAME, DB_SU, DB_SU_PW)
            print "dropped user '%s'" % NAME;
    elif not user_exists and database_exists:
        print "No user named '%s' found." % NAME
        if drutils.confirm_with_yes("really drop database '%s'? [NO|yes] " % NAME):
            drutils.drop_database(NAME, DB_SU, DB_SU_PW)
            print "dropped database '%s'" % NAME;
    elif user_exists and not database_exists:
        print "No database named '%s' found." % NAME
        if drutils.confirm_with_yes("really drop user '%s'? [NO|yes] " % NAME):
            drutils.drop_user(NAME, DB_SU, DB_SU_PW)
            print "dropped user '%s'" % NAME;
    else:
        print "No database or user named '%s' found." % NAME;
