#! /usr/bin/python

# Script to print out all the current MySql databases.  See README.md
# for more details.
#
# Author: Mark Phillips <mphillip@unca.edu>

import sys, re, os
sys.path.append(".") # this line gets replaced by `make install`
import drutils

def usage():
    print "usage: dblist [--dbsu=USER:PASSWORD]"
    sys.exit(-1)

if __name__ == "__main__":
    #
    # Process the arguments
    #
    DB_SU    = None
    DB_SU_PW = None
    sys.argv.pop(0)
    while True:
        if len(sys.argv)==0:
            break
        arg = sys.argv.pop(0)
        if arg.startswith("--dbsu"):
            match = re.match(r'^--dbsu=([^:]+):(.*)$', arg)
            if match:
                DB_SU    = match.group(1)
                DB_SU_PW = match.group(2)
            else:
                usage()
        else:
            usage()
    #
    # If we didn't get DB_SU info from the args, check for it in environment vars:
    # 
    if DB_SU==None:
        try:
            DB_SU    = os.environ['DRUTILS_DB_SU']
            DB_SU_PW = os.environ['DRUTILS_DB_SU_PW']
        except:
            pass
    #
    # Print out the databases
    #
    print "\n".join(drutils.get_databases(DB_SU, DB_SU_PW))
